// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: order_data.proto

package order_data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderDataService_GetOrderData_FullMethodName = "/order_data.OrderDataService/GetOrderData"
)

// OrderDataServiceClient is the client API for OrderDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderDataServiceClient interface {
	GetOrderData(ctx context.Context, in *OrderDataRequest, opts ...grpc.CallOption) (*OrderDataResponse, error)
}

type orderDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderDataServiceClient(cc grpc.ClientConnInterface) OrderDataServiceClient {
	return &orderDataServiceClient{cc}
}

func (c *orderDataServiceClient) GetOrderData(ctx context.Context, in *OrderDataRequest, opts ...grpc.CallOption) (*OrderDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderDataResponse)
	err := c.cc.Invoke(ctx, OrderDataService_GetOrderData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderDataServiceServer is the server API for OrderDataService service.
// All implementations must embed UnimplementedOrderDataServiceServer
// for forward compatibility.
type OrderDataServiceServer interface {
	GetOrderData(context.Context, *OrderDataRequest) (*OrderDataResponse, error)
	mustEmbedUnimplementedOrderDataServiceServer()
}

// UnimplementedOrderDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderDataServiceServer struct{}

func (UnimplementedOrderDataServiceServer) GetOrderData(context.Context, *OrderDataRequest) (*OrderDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderData not implemented")
}
func (UnimplementedOrderDataServiceServer) mustEmbedUnimplementedOrderDataServiceServer() {}
func (UnimplementedOrderDataServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderDataServiceServer will
// result in compilation errors.
type UnsafeOrderDataServiceServer interface {
	mustEmbedUnimplementedOrderDataServiceServer()
}

func RegisterOrderDataServiceServer(s grpc.ServiceRegistrar, srv OrderDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderDataService_ServiceDesc, srv)
}

func _OrderDataService_GetOrderData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderDataServiceServer).GetOrderData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderDataService_GetOrderData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderDataServiceServer).GetOrderData(ctx, req.(*OrderDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderDataService_ServiceDesc is the grpc.ServiceDesc for OrderDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_data.OrderDataService",
	HandlerType: (*OrderDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderData",
			Handler:    _OrderDataService_GetOrderData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_data.proto",
}
