apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment-v4
  labels:
    app: orders
    version: v4
spec:
  replicas: 1  # Число реплик приложения
  selector:
    matchLabels:
      app: orders
      version: v4
  template:
    metadata:
      labels:
        app: orders
        version: v4
    spec:
      containers:
        - name: config-mock
          image: cr.yandex/crpatchv2fnnbum2cdu7/orders:v4
          ports:
            - containerPort: 8080
