apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment-v1
  labels:
    app: orders
    version: v1
spec:
  replicas: 1  # Число реплик приложения
  selector:
    matchLabels:
      app: orders
      version: v1
  template:
    metadata:
      labels:
        app: orders
        version: v1
    spec:
      containers:
        - name: config-mock
          image: cr.yandex/crpatchv2fnnbum2cdu7/orders:v1
          ports:
            - containerPort: 8080
