apiVersion: apps/v1
kind: Deployment
metadata:
  name: sources-deployment-v1
  labels:
    app: sources
    version: v1
spec:
  replicas: 1  # Число реплик приложения
  selector:
    matchLabels:
      app: sources
      version: v1
  template:
    metadata:
      labels:
        app: sources
        version: v1
    spec:
      containers:
        - name: config-mock
          image: cr.yandex/crpatchv2fnnbum2cdu7/sources:v1
          ports:
            - containerPort: 9000
