apiVersion: v1
kind: Service
metadata:
  name: sources-service
spec:
  type: LoadBalancer  # Сервис будет доступен через внешний IP
  selector:
    app: sources
  ports:
    - name: grpc-9000
      protocol: TCP
      port: 9000 # Внешний порт для доступа
      targetPort: 9000 # Порт внутри контейнера
