apiVersion: v1
kind: Service
metadata:
  name: order-data-mock-service
spec:
  type: LoadBalancer  # Сервис будет доступен через внешний IP
  selector:
    app: order-data-mock
  ports:
    - protocol: TCP
      port: 9091 # Внешний порт для доступа
      targetPort: 9091 # Порт внутри контейнера
  sessionAffinity: None
