FROM python:3.9-slim

WORKDIR /app
COPY main.py .
COPY executor_profile_pb2_grpc.py .
COPY executor_profile_pb2.py .
RUN pip install grpcio grpcio-tools grpcio-reflection
EXPOSE 50051
CMD ["python3", "main.py"]
