// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: order_data.proto

package order_data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderDataServiceClient is the client API for OrderDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderDataServiceClient interface {
	GetOrderData(ctx context.Context, in *OrderDataRequest, opts ...grpc.CallOption) (*OrderDataResponse, error)
}

type orderDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderDataServiceClient(cc grpc.ClientConnInterface) OrderDataServiceClient {
	return &orderDataServiceClient{cc}
}

func (c *orderDataServiceClient) GetOrderData(ctx context.Context, in *OrderDataRequest, opts ...grpc.CallOption) (*OrderDataResponse, error) {
	out := new(OrderDataResponse)
	err := c.cc.Invoke(ctx, "/order_data.OrderDataService/GetOrderData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderDataServiceServer is the server API for OrderDataService service.
// All implementations must embed UnimplementedOrderDataServiceServer
// for forward compatibility
type OrderDataServiceServer interface {
	GetOrderData(context.Context, *OrderDataRequest) (*OrderDataResponse, error)
	mustEmbedUnimplementedOrderDataServiceServer()
}

// UnimplementedOrderDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderDataServiceServer struct {
}

func (UnimplementedOrderDataServiceServer) GetOrderData(context.Context, *OrderDataRequest) (*OrderDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderData not implemented")
}
func (UnimplementedOrderDataServiceServer) mustEmbedUnimplementedOrderDataServiceServer() {}

// UnsafeOrderDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderDataServiceServer will
// result in compilation errors.
type UnsafeOrderDataServiceServer interface {
	mustEmbedUnimplementedOrderDataServiceServer()
}

func RegisterOrderDataServiceServer(s grpc.ServiceRegistrar, srv OrderDataServiceServer) {
	s.RegisterService(&OrderDataService_ServiceDesc, srv)
}

func _OrderDataService_GetOrderData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderDataServiceServer).GetOrderData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order_data.OrderDataService/GetOrderData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderDataServiceServer).GetOrderData(ctx, req.(*OrderDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderDataService_ServiceDesc is the grpc.ServiceDesc for OrderDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_data.OrderDataService",
	HandlerType: (*OrderDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderData",
			Handler:    _OrderDataService_GetOrderData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_data.proto",
}
