// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: executor_profile.proto

package executor_profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutorProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecutorId string `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
}

func (x *ExecutorProfileRequest) Reset() {
	*x = ExecutorProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_executor_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutorProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorProfileRequest) ProtoMessage() {}

func (x *ExecutorProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorProfileRequest.ProtoReflect.Descriptor instead.
func (*ExecutorProfileRequest) Descriptor() ([]byte, []int) {
	return file_executor_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutorProfileRequest) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

type ExecutorProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags   []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Rating float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *ExecutorProfileResponse) Reset() {
	*x = ExecutorProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_executor_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutorProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutorProfileResponse) ProtoMessage() {}

func (x *ExecutorProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutorProfileResponse.ProtoReflect.Descriptor instead.
func (*ExecutorProfileResponse) Descriptor() ([]byte, []int) {
	return file_executor_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutorProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutorProfileResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ExecutorProfileResponse) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_executor_profile_proto protoreflect.FileDescriptor

var file_executor_profile_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x39, 0x0a, 0x16, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x17, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x32, 0x83, 0x01, 0x0a,
	0x16, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x28, 0x2e,
	0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_executor_profile_proto_rawDescOnce sync.Once
	file_executor_profile_proto_rawDescData = file_executor_profile_proto_rawDesc
)

func file_executor_profile_proto_rawDescGZIP() []byte {
	file_executor_profile_proto_rawDescOnce.Do(func() {
		file_executor_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_executor_profile_proto_rawDescData)
	})
	return file_executor_profile_proto_rawDescData
}

var file_executor_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_executor_profile_proto_goTypes = []interface{}{
	(*ExecutorProfileRequest)(nil),  // 0: executor_profile.ExecutorProfileRequest
	(*ExecutorProfileResponse)(nil), // 1: executor_profile.ExecutorProfileResponse
}
var file_executor_profile_proto_depIdxs = []int32{
	0, // 0: executor_profile.ExecutorProfileService.GetExecutorProfile:input_type -> executor_profile.ExecutorProfileRequest
	1, // 1: executor_profile.ExecutorProfileService.GetExecutorProfile:output_type -> executor_profile.ExecutorProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_executor_profile_proto_init() }
func file_executor_profile_proto_init() {
	if File_executor_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_executor_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutorProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_executor_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutorProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_executor_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_profile_proto_goTypes,
		DependencyIndexes: file_executor_profile_proto_depIdxs,
		MessageInfos:      file_executor_profile_proto_msgTypes,
	}.Build()
	File_executor_profile_proto = out.File
	file_executor_profile_proto_rawDesc = nil
	file_executor_profile_proto_goTypes = nil
	file_executor_profile_proto_depIdxs = nil
}
