// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: sources.proto

package origins

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OriginsServiceClient is the client API for OriginsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OriginsServiceClient interface {
	GetOrderInfo(ctx context.Context, in *OriginsRequest, opts ...grpc.CallOption) (*OriginsResponse, error)
}

type originsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOriginsServiceClient(cc grpc.ClientConnInterface) OriginsServiceClient {
	return &originsServiceClient{cc}
}

func (c *originsServiceClient) GetOrderInfo(ctx context.Context, in *OriginsRequest, opts ...grpc.CallOption) (*OriginsResponse, error) {
	out := new(OriginsResponse)
	err := c.cc.Invoke(ctx, "/sources.OriginsService/GetOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OriginsServiceServer is the server API for OriginsService service.
// All implementations must embed UnimplementedOriginsServiceServer
// for forward compatibility
type OriginsServiceServer interface {
	GetOrderInfo(context.Context, *OriginsRequest) (*OriginsResponse, error)
	mustEmbedUnimplementedOriginsServiceServer()
}

// UnimplementedOriginsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOriginsServiceServer struct {
}

func (UnimplementedOriginsServiceServer) GetOrderInfo(context.Context, *OriginsRequest) (*OriginsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderInfo not implemented")
}
func (UnimplementedOriginsServiceServer) mustEmbedUnimplementedOriginsServiceServer() {}

// UnsafeOriginsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OriginsServiceServer will
// result in compilation errors.
type UnsafeOriginsServiceServer interface {
	mustEmbedUnimplementedOriginsServiceServer()
}

func RegisterOriginsServiceServer(s grpc.ServiceRegistrar, srv OriginsServiceServer) {
	s.RegisterService(&OriginsService_ServiceDesc, srv)
}

func _OriginsService_GetOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OriginsServiceServer).GetOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sources.OriginsService/GetOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OriginsServiceServer).GetOrderInfo(ctx, req.(*OriginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OriginsService_ServiceDesc is the grpc.ServiceDesc for OriginsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OriginsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sources.OriginsService",
	HandlerType: (*OriginsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderInfo",
			Handler:    _OriginsService_GetOrderInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sources.proto",
}
