apiVersion: v1
kind: Service
metadata:
  name: config-mock-service
spec:
  type: LoadBalancer  # Сервис будет доступен через внешний IP
  selector:
    app: config-mock
  ports:
    - protocol: TCP
      port: 9090 # Внешний порт для доступа
      targetPort: 9090 # Порт внутри контейнера
  sessionAffinity: None
