// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: zone_data.proto

package zone_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZoneDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneId string `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
}

func (x *ZoneDataRequest) Reset() {
	*x = ZoneDataRequest{}
	mi := &file_zone_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneDataRequest) ProtoMessage() {}

func (x *ZoneDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zone_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneDataRequest.ProtoReflect.Descriptor instead.
func (*ZoneDataRequest) Descriptor() ([]byte, []int) {
	return file_zone_data_proto_rawDescGZIP(), []int{0}
}

func (x *ZoneDataRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

type ZoneDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZoneId      string  `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	CoinCoeff   float32 `protobuf:"fixed32,2,opt,name=coin_coeff,json=coinCoeff,proto3" json:"coin_coeff,omitempty"`
	DisplayName string  `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
}

func (x *ZoneDataResponse) Reset() {
	*x = ZoneDataResponse{}
	mi := &file_zone_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoneDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoneDataResponse) ProtoMessage() {}

func (x *ZoneDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zone_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoneDataResponse.ProtoReflect.Descriptor instead.
func (*ZoneDataResponse) Descriptor() ([]byte, []int) {
	return file_zone_data_proto_rawDescGZIP(), []int{1}
}

func (x *ZoneDataResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *ZoneDataResponse) GetCoinCoeff() float32 {
	if x != nil {
		return x.CoinCoeff
	}
	return 0
}

func (x *ZoneDataResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_zone_data_proto protoreflect.FileDescriptor

var file_zone_data_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2a, 0x0a, 0x0f,
	0x5a, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x10, 0x5a, 0x6f, 0x6e, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x7a,
	0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x63, 0x6f,
	0x65, 0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x43,
	0x6f, 0x65, 0x66, 0x66, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x59, 0x0a, 0x0f, 0x5a, 0x6f, 0x6e, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x5a, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x7a, 0x6f, 0x6e, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x5a, 0x6f, 0x6e, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zone_data_proto_rawDescOnce sync.Once
	file_zone_data_proto_rawDescData = file_zone_data_proto_rawDesc
)

func file_zone_data_proto_rawDescGZIP() []byte {
	file_zone_data_proto_rawDescOnce.Do(func() {
		file_zone_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_zone_data_proto_rawDescData)
	})
	return file_zone_data_proto_rawDescData
}

var file_zone_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_zone_data_proto_goTypes = []any{
	(*ZoneDataRequest)(nil),  // 0: zone_data.ZoneDataRequest
	(*ZoneDataResponse)(nil), // 1: zone_data.ZoneDataResponse
}
var file_zone_data_proto_depIdxs = []int32{
	0, // 0: zone_data.ZoneDataService.GetZoneData:input_type -> zone_data.ZoneDataRequest
	1, // 1: zone_data.ZoneDataService.GetZoneData:output_type -> zone_data.ZoneDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zone_data_proto_init() }
func file_zone_data_proto_init() {
	if File_zone_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zone_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zone_data_proto_goTypes,
		DependencyIndexes: file_zone_data_proto_depIdxs,
		MessageInfos:      file_zone_data_proto_msgTypes,
	}.Build()
	File_zone_data_proto = out.File
	file_zone_data_proto_rawDesc = nil
	file_zone_data_proto_goTypes = nil
	file_zone_data_proto_depIdxs = nil
}
