# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x06\x63onfig\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x0e\x43onfigResponse\x12\x36\n\x13\x63oin_coeff_settings\x18\x01 \x01(\x0b\x32\x19.config.CoinCoeffSettings\"6\n\x11\x43oinCoeffSettings\x12\x0f\n\x07maximum\x18\x01 \x01(\x02\x12\x10\n\x08\x66\x61llback\x18\x02 \x01(\x02\x32L\n\rConfigService\x12;\n\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x16.config.ConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGRESPONSE']._serialized_start=53
  _globals['_CONFIGRESPONSE']._serialized_end=125
  _globals['_COINCOEFFSETTINGS']._serialized_start=127
  _globals['_COINCOEFFSETTINGS']._serialized_end=181
  _globals['_CONFIGSERVICE']._serialized_start=183
  _globals['_CONFIGSERVICE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
