# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x06\x63onfig\x1a\x1bgoogle/protobuf/empty.proto\"y\n\x0e\x43onfigResponse\x12\x36\n\x08settings\x18\x01 \x03(\x0b\x32$.config.ConfigResponse.SettingsEntry\x1a/\n\rSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32L\n\rConfigService\x12;\n\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x16.config.ConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGRESPONSE_SETTINGSENTRY']._loaded_options = None
  _globals['_CONFIGRESPONSE_SETTINGSENTRY']._serialized_options = b'8\001'
  _globals['_CONFIGRESPONSE']._serialized_start=53
  _globals['_CONFIGRESPONSE']._serialized_end=174
  _globals['_CONFIGRESPONSE_SETTINGSENTRY']._serialized_start=127
  _globals['_CONFIGRESPONSE_SETTINGSENTRY']._serialized_end=174
  _globals['_CONFIGSERVICE']._serialized_start=176
  _globals['_CONFIGSERVICE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
