# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import executor_profile_pb2 as executor__profile__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in executor_profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExecutorProfile = channel.unary_unary(
                '/executor_profile.ExecutorProfileService/GetExecutorProfile',
                request_serializer=executor__profile__pb2.ExecutorProfileRequest.SerializeToString,
                response_deserializer=executor__profile__pb2.ExecutorProfileResponse.FromString,
                _registered_method=True)


class ExecutorProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExecutorProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExecutorProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutorProfile,
                    request_deserializer=executor__profile__pb2.ExecutorProfileRequest.FromString,
                    response_serializer=executor__profile__pb2.ExecutorProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'executor_profile.ExecutorProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('executor_profile.ExecutorProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExecutorProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExecutorProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/executor_profile.ExecutorProfileService/GetExecutorProfile',
            executor__profile__pb2.ExecutorProfileRequest.SerializeToString,
            executor__profile__pb2.ExecutorProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
