# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'order_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10order_data.proto\x12\norder_data\"$\n\x10OrderDataRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"a\n\x11OrderDataResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07zone_id\x18\x03 \x01(\t\x12\x18\n\x10\x62\x61se_coin_amount\x18\x04 \x01(\x02\x32_\n\x10OrderDataService\x12K\n\x0cGetOrderData\x12\x1c.order_data.OrderDataRequest\x1a\x1d.order_data.OrderDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERDATAREQUEST']._serialized_start=32
  _globals['_ORDERDATAREQUEST']._serialized_end=68
  _globals['_ORDERDATARESPONSE']._serialized_start=70
  _globals['_ORDERDATARESPONSE']._serialized_end=167
  _globals['_ORDERDATASERVICE']._serialized_start=169
  _globals['_ORDERDATASERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
