# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zone_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'zone_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fzone_data.proto\x12\tzone_data\"\"\n\x0fZoneDataRequest\x12\x0f\n\x07zone_id\x18\x01 \x01(\t\"M\n\x10ZoneDataResponse\x12\x0f\n\x07zone_id\x18\x01 \x01(\t\x12\x12\n\ncoin_coeff\x18\x02 \x01(\x02\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t2Y\n\x0fZoneDataService\x12\x46\n\x0bGetZoneData\x12\x1a.zone_data.ZoneDataRequest\x1a\x1b.zone_data.ZoneDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zone_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ZONEDATAREQUEST']._serialized_start=30
  _globals['_ZONEDATAREQUEST']._serialized_end=64
  _globals['_ZONEDATARESPONSE']._serialized_start=66
  _globals['_ZONEDATARESPONSE']._serialized_end=143
  _globals['_ZONEDATASERVICE']._serialized_start=145
  _globals['_ZONEDATASERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
